/********************************************************************************
** Form generated from reading UI file 'nizar.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NIZAR_H
#define UI_NIZAR_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QTabWidget *ges;
    QWidget *tab;
    QTabWidget *tabWidget_2;
    QWidget *tab_4;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLineEdit *referancePoss;
    QLineEdit *nomPoss;
    QRadioButton *ajouterEtatMateriauxPoss1;
    QRadioButton *ajouteretatMateriauxposs0;
    QLabel *label_84;
    QPushButton *ajouterposs;
    QComboBox *comboetatajouter;
    QWidget *tab_6;
    QLabel *label_83;
    QPushButton *pushButton_4;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLineEdit *mat_poss_nom_mod;
    QLineEdit *mat_poss_reff_mod;
    QRadioButton *mat_poss_etat_b_mod;
    QRadioButton *mat_poss_m__mod;
    QWidget *tab_7;
    QLabel *label_8;
    QLineEdit *ref_mat_poss_a_supp1;
    QLabel *label_82;
    QPushButton *supp_mat_poss1;
    QWidget *tab_5;
    QTableView *tableView;
    QLabel *label_9;
    QLabel *label_10;
    QLineEdit *lineEdit_4;
    QLabel *label_81;
    QPushButton *pushButton_10;
    QComboBox *comboBox_5;
    QPushButton *pushButton_13;
    QLabel *label_37;
    QPushButton *pushButton_14;
    QLabel *label_39;
    QWidget *tab_2;
    QTabWidget *tabWidget_6;
    QWidget *tab_20;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *refmatmanq;
    QLineEdit *nommanq;
    QLabel *label_23;
    QLineEdit *prixmanq;
    QLabel *label_88;
    QPushButton *ajoutermateriauxmanq;
    QLabel *label_7;
    QRadioButton *dispo_oui;
    QRadioButton *dispo_non;
    QWidget *tab_21;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLabel *label_85;
    QPushButton *pushButton_5;
    QLabel *label_24;
    QRadioButton *radioButton_9;
    QRadioButton *radioButton_10;
    QWidget *tab_22;
    QLabel *label_28;
    QLineEdit *ref_mat_manq_a_supp1;
    QLabel *label_86;
    QPushButton *supprimermatmanq1;
    QWidget *tab_23;
    QTableView *tableView_3;
    QLabel *label_29;
    QLabel *label_30;
    QLineEdit *lineEdit_12;
    QLabel *label_87;
    QPushButton *pushButton_11;
    QComboBox *comboBox_4;
    QLabel *label_50;
    QPushButton *pushButton_19;
    QLabel *label_36;
    QWidget *tab_3;
    QTabWidget *tabWidget_5;
    QWidget *tab_16;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *ref_mat_maint_a_ajouter;
    QLineEdit *nom_mat_maint_a_ajouter;
    QLabel *label_13;
    QLabel *label_31;
    QLineEdit *region_mat_maint_a_ajouter;
    QDateTimeEdit *dateTimeEdit;
    QLabel *label_78;
    QPushButton *ajouter_mat_maintenace;
    QFrame *frame;
    QWidget *tab_17;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLabel *label_17;
    QLineEdit *lineEdit_21;
    QLabel *label_34;
    QLabel *label_35;
    QDateTimeEdit *dateTimeEdit_3;
    QLabel *label_38;
    QDateTimeEdit *dateTimeEdit_4;
    QLabel *label_77;
    QPushButton *pushButton_6;
    QWidget *tab_18;
    QLabel *label_18;
    QLineEdit *ref_mat_maint_a_supp1;
    QLabel *label_79;
    QPushButton *supprimer_mat_maintenace1;
    QWidget *tab_19;
    QTableView *tableView_2;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *lineEdit_8;
    QLabel *label_80;
    QPushButton *pushButton_12;
    QComboBox *comboBox_3;
    QLabel *label_51;
    QPushButton *pushButton_20;
    QLabel *label_14;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QString::fromUtf8("Dialog"));
        Dialog->resize(753, 438);
        ges = new QTabWidget(Dialog);
        ges->setObjectName(QString::fromUtf8("ges"));
        ges->setGeometry(QRect(10, 10, 731, 391));
        QFont font;
        font.setFamily(QString::fromUtf8("Microsoft Tai Le"));
        ges->setFont(font);
        ges->setTabShape(QTabWidget::Triangular);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tabWidget_2 = new QTabWidget(tab);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(20, 30, 681, 301));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Microsoft YaHei UI"));
        tabWidget_2->setFont(font1);
        tabWidget_2->setLayoutDirection(Qt::LeftToRight);
        tabWidget_2->setTabPosition(QTabWidget::North);
        tabWidget_2->setTabShape(QTabWidget::Triangular);
        tabWidget_2->setElideMode(Qt::ElideLeft);
        tabWidget_2->setDocumentMode(false);
        tabWidget_2->setTabsClosable(false);
        tabWidget_2->setMovable(false);
        tabWidget_2->setTabBarAutoHide(false);
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label = new QLabel(tab_4);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(190, 30, 61, 21));
        label_2 = new QLabel(tab_4);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(150, 70, 101, 21));
        label_3 = new QLabel(tab_4);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(210, 130, 51, 21));
        referancePoss = new QLineEdit(tab_4);
        referancePoss->setObjectName(QString::fromUtf8("referancePoss"));
        referancePoss->setGeometry(QRect(260, 30, 113, 20));
        nomPoss = new QLineEdit(tab_4);
        nomPoss->setObjectName(QString::fromUtf8("nomPoss"));
        nomPoss->setGeometry(QRect(260, 70, 113, 20));
        ajouterEtatMateriauxPoss1 = new QRadioButton(tab_4);
        ajouterEtatMateriauxPoss1->setObjectName(QString::fromUtf8("ajouterEtatMateriauxPoss1"));
        ajouterEtatMateriauxPoss1->setGeometry(QRect(250, 130, 81, 21));
        ajouteretatMateriauxposs0 = new QRadioButton(tab_4);
        ajouteretatMateriauxposs0->setObjectName(QString::fromUtf8("ajouteretatMateriauxposs0"));
        ajouteretatMateriauxposs0->setGeometry(QRect(340, 130, 91, 21));
        label_84 = new QLabel(tab_4);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(0, 0, 681, 281));
        label_84->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        ajouterposs = new QPushButton(tab_4);
        ajouterposs->setObjectName(QString::fromUtf8("ajouterposs"));
        ajouterposs->setGeometry(QRect(570, 240, 75, 23));
        ajouterposs->setMouseTracking(true);
        ajouterposs->setFocusPolicy(Qt::ClickFocus);
        comboetatajouter = new QComboBox(tab_4);
        comboetatajouter->addItem(QString());
        comboetatajouter->addItem(QString());
        comboetatajouter->setObjectName(QString::fromUtf8("comboetatajouter"));
        comboetatajouter->setGeometry(QRect(300, 170, 69, 22));
        tabWidget_2->addTab(tab_4, QString());
        label_84->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        referancePoss->raise();
        nomPoss->raise();
        ajouterEtatMateriauxPoss1->raise();
        ajouteretatMateriauxposs0->raise();
        ajouterposs->raise();
        comboetatajouter->raise();
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        label_83 = new QLabel(tab_6);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(0, 0, 681, 281));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Arial Rounded MT Bold"));
        label_83->setFont(font2);
        label_83->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        pushButton_4 = new QPushButton(tab_6);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(580, 240, 75, 23));
        pushButton_4->setFocusPolicy(Qt::ClickFocus);
        label_4 = new QLabel(tab_6);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(170, 40, 51, 21));
        label_5 = new QLabel(tab_6);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(170, 120, 71, 41));
        label_6 = new QLabel(tab_6);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(170, 70, 91, 41));
        mat_poss_nom_mod = new QLineEdit(tab_6);
        mat_poss_nom_mod->setObjectName(QString::fromUtf8("mat_poss_nom_mod"));
        mat_poss_nom_mod->setGeometry(QRect(280, 80, 113, 20));
        mat_poss_reff_mod = new QLineEdit(tab_6);
        mat_poss_reff_mod->setObjectName(QString::fromUtf8("mat_poss_reff_mod"));
        mat_poss_reff_mod->setGeometry(QRect(280, 40, 113, 20));
        mat_poss_etat_b_mod = new QRadioButton(tab_6);
        mat_poss_etat_b_mod->setObjectName(QString::fromUtf8("mat_poss_etat_b_mod"));
        mat_poss_etat_b_mod->setGeometry(QRect(240, 130, 91, 21));
        mat_poss_m__mod = new QRadioButton(tab_6);
        mat_poss_m__mod->setObjectName(QString::fromUtf8("mat_poss_m__mod"));
        mat_poss_m__mod->setGeometry(QRect(330, 130, 91, 21));
        tabWidget_2->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        label_8 = new QLabel(tab_7);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 120, 211, 21));
        ref_mat_poss_a_supp1 = new QLineEdit(tab_7);
        ref_mat_poss_a_supp1->setObjectName(QString::fromUtf8("ref_mat_poss_a_supp1"));
        ref_mat_poss_a_supp1->setGeometry(QRect(250, 120, 113, 20));
        label_82 = new QLabel(tab_7);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(0, 0, 681, 281));
        label_82->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        supp_mat_poss1 = new QPushButton(tab_7);
        supp_mat_poss1->setObjectName(QString::fromUtf8("supp_mat_poss1"));
        supp_mat_poss1->setGeometry(QRect(550, 230, 75, 23));
        supp_mat_poss1->setFocusPolicy(Qt::ClickFocus);
        tabWidget_2->addTab(tab_7, QString());
        label_82->raise();
        label_8->raise();
        ref_mat_poss_a_supp1->raise();
        supp_mat_poss1->raise();
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tableView = new QTableView(tab_5);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(10, 10, 351, 251));
        label_9 = new QLabel(tab_5);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(380, 20, 51, 21));
        label_10 = new QLabel(tab_5);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(370, 110, 71, 21));
        lineEdit_4 = new QLineEdit(tab_5);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(440, 110, 113, 21));
        label_81 = new QLabel(tab_5);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(0, 0, 681, 281));
        label_81->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        pushButton_10 = new QPushButton(tab_5);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(560, 112, 81, 21));
        pushButton_10->setFocusPolicy(Qt::ClickFocus);
        comboBox_5 = new QComboBox(tab_5);
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->setObjectName(QString::fromUtf8("comboBox_5"));
        comboBox_5->setGeometry(QRect(440, 20, 69, 22));
        comboBox_5->setFocusPolicy(Qt::ClickFocus);
        pushButton_13 = new QPushButton(tab_5);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(540, 20, 75, 23));
        pushButton_13->setFocusPolicy(Qt::ClickFocus);
        label_37 = new QLabel(tab_5);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(390, 200, 251, 21));
        pushButton_14 = new QPushButton(tab_5);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(470, 230, 75, 23));
        pushButton_14->setFocusPolicy(Qt::ClickFocus);
        tabWidget_2->addTab(tab_5, QString());
        label_81->raise();
        tableView->raise();
        label_9->raise();
        label_10->raise();
        lineEdit_4->raise();
        pushButton_10->raise();
        comboBox_5->raise();
        pushButton_13->raise();
        label_37->raise();
        pushButton_14->raise();
        label_39 = new QLabel(tab);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(-10, -170, 771, 711));
        label_39->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/back.jpg")));
        ges->addTab(tab, QString());
        label_39->raise();
        tabWidget_2->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tabWidget_6 = new QTabWidget(tab_2);
        tabWidget_6->setObjectName(QString::fromUtf8("tabWidget_6"));
        tabWidget_6->setGeometry(QRect(20, 30, 681, 301));
        tabWidget_6->setTabShape(QTabWidget::Triangular);
        tab_20 = new QWidget();
        tab_20->setObjectName(QString::fromUtf8("tab_20"));
        label_21 = new QLabel(tab_20);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(190, 30, 61, 21));
        label_22 = new QLabel(tab_20);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(120, 80, 141, 21));
        refmatmanq = new QLineEdit(tab_20);
        refmatmanq->setObjectName(QString::fromUtf8("refmatmanq"));
        refmatmanq->setGeometry(QRect(270, 30, 113, 20));
        nommanq = new QLineEdit(tab_20);
        nommanq->setObjectName(QString::fromUtf8("nommanq"));
        nommanq->setGeometry(QRect(270, 80, 113, 20));
        label_23 = new QLabel(tab_20);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(220, 130, 51, 21));
        prixmanq = new QLineEdit(tab_20);
        prixmanq->setObjectName(QString::fromUtf8("prixmanq"));
        prixmanq->setGeometry(QRect(270, 130, 113, 20));
        label_88 = new QLabel(tab_20);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(0, 0, 681, 281));
        label_88->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        ajoutermateriauxmanq = new QPushButton(tab_20);
        ajoutermateriauxmanq->setObjectName(QString::fromUtf8("ajoutermateriauxmanq"));
        ajoutermateriauxmanq->setGeometry(QRect(570, 240, 75, 23));
        label_7 = new QLabel(tab_20);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(180, 180, 71, 20));
        dispo_oui = new QRadioButton(tab_20);
        dispo_oui->setObjectName(QString::fromUtf8("dispo_oui"));
        dispo_oui->setGeometry(QRect(270, 180, 91, 20));
        dispo_non = new QRadioButton(tab_20);
        dispo_non->setObjectName(QString::fromUtf8("dispo_non"));
        dispo_non->setGeometry(QRect(340, 180, 91, 21));
        tabWidget_6->addTab(tab_20, QString());
        label_88->raise();
        label_21->raise();
        label_22->raise();
        refmatmanq->raise();
        nommanq->raise();
        label_23->raise();
        prixmanq->raise();
        ajoutermateriauxmanq->raise();
        label_7->raise();
        dispo_oui->raise();
        dispo_non->raise();
        tab_21 = new QWidget();
        tab_21->setObjectName(QString::fromUtf8("tab_21"));
        label_25 = new QLabel(tab_21);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(230, 30, 91, 21));
        label_26 = new QLabel(tab_21);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(210, 80, 131, 21));
        label_27 = new QLabel(tab_21);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(250, 130, 81, 21));
        lineEdit_23 = new QLineEdit(tab_21);
        lineEdit_23->setObjectName(QString::fromUtf8("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(310, 30, 113, 20));
        lineEdit_24 = new QLineEdit(tab_21);
        lineEdit_24->setObjectName(QString::fromUtf8("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(310, 80, 113, 20));
        lineEdit_25 = new QLineEdit(tab_21);
        lineEdit_25->setObjectName(QString::fromUtf8("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(310, 130, 113, 20));
        label_85 = new QLabel(tab_21);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(-10, 0, 681, 281));
        label_85->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        pushButton_5 = new QPushButton(tab_21);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(580, 240, 75, 23));
        label_24 = new QLabel(tab_21);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(220, 180, 71, 20));
        radioButton_9 = new QRadioButton(tab_21);
        radioButton_9->setObjectName(QString::fromUtf8("radioButton_9"));
        radioButton_9->setGeometry(QRect(300, 180, 91, 20));
        radioButton_10 = new QRadioButton(tab_21);
        radioButton_10->setObjectName(QString::fromUtf8("radioButton_10"));
        radioButton_10->setGeometry(QRect(380, 180, 91, 20));
        tabWidget_6->addTab(tab_21, QString());
        label_85->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        lineEdit_23->raise();
        lineEdit_24->raise();
        lineEdit_25->raise();
        pushButton_5->raise();
        label_24->raise();
        radioButton_9->raise();
        radioButton_10->raise();
        tab_22 = new QWidget();
        tab_22->setObjectName(QString::fromUtf8("tab_22"));
        label_28 = new QLabel(tab_22);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 120, 211, 21));
        ref_mat_manq_a_supp1 = new QLineEdit(tab_22);
        ref_mat_manq_a_supp1->setObjectName(QString::fromUtf8("ref_mat_manq_a_supp1"));
        ref_mat_manq_a_supp1->setGeometry(QRect(260, 120, 113, 20));
        label_86 = new QLabel(tab_22);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(0, 0, 681, 281));
        label_86->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        supprimermatmanq1 = new QPushButton(tab_22);
        supprimermatmanq1->setObjectName(QString::fromUtf8("supprimermatmanq1"));
        supprimermatmanq1->setGeometry(QRect(570, 240, 75, 23));
        tabWidget_6->addTab(tab_22, QString());
        label_86->raise();
        label_28->raise();
        ref_mat_manq_a_supp1->raise();
        supprimermatmanq1->raise();
        tab_23 = new QWidget();
        tab_23->setObjectName(QString::fromUtf8("tab_23"));
        tableView_3 = new QTableView(tab_23);
        tableView_3->setObjectName(QString::fromUtf8("tableView_3"));
        tableView_3->setGeometry(QRect(10, 10, 351, 251));
        label_29 = new QLabel(tab_23);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(390, 20, 51, 21));
        label_30 = new QLabel(tab_23);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(370, 90, 71, 21));
        lineEdit_12 = new QLineEdit(tab_23);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(440, 90, 113, 20));
        label_87 = new QLabel(tab_23);
        label_87->setObjectName(QString::fromUtf8("label_87"));
        label_87->setGeometry(QRect(0, 0, 691, 291));
        label_87->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        pushButton_11 = new QPushButton(tab_23);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(570, 90, 75, 23));
        comboBox_4 = new QComboBox(tab_23);
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->setObjectName(QString::fromUtf8("comboBox_4"));
        comboBox_4->setGeometry(QRect(450, 20, 69, 22));
        label_50 = new QLabel(tab_23);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(390, 180, 261, 31));
        pushButton_19 = new QPushButton(tab_23);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(480, 220, 75, 23));
        tabWidget_6->addTab(tab_23, QString());
        label_87->raise();
        tableView_3->raise();
        label_29->raise();
        label_30->raise();
        lineEdit_12->raise();
        pushButton_11->raise();
        comboBox_4->raise();
        label_50->raise();
        pushButton_19->raise();
        label_36 = new QLabel(tab_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(0, 0, 741, 371));
        label_36->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/back.jpg")));
        ges->addTab(tab_2, QString());
        label_36->raise();
        tabWidget_6->raise();
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        tabWidget_5 = new QTabWidget(tab_3);
        tabWidget_5->setObjectName(QString::fromUtf8("tabWidget_5"));
        tabWidget_5->setGeometry(QRect(20, 30, 681, 301));
        tabWidget_5->setTabShape(QTabWidget::Triangular);
        tab_16 = new QWidget();
        tab_16->setObjectName(QString::fromUtf8("tab_16"));
        label_11 = new QLabel(tab_16);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(250, 30, 61, 21));
        label_12 = new QLabel(tab_16);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(220, 70, 91, 21));
        ref_mat_maint_a_ajouter = new QLineEdit(tab_16);
        ref_mat_maint_a_ajouter->setObjectName(QString::fromUtf8("ref_mat_maint_a_ajouter"));
        ref_mat_maint_a_ajouter->setGeometry(QRect(320, 30, 113, 20));
        nom_mat_maint_a_ajouter = new QLineEdit(tab_16);
        nom_mat_maint_a_ajouter->setObjectName(QString::fromUtf8("nom_mat_maint_a_ajouter"));
        nom_mat_maint_a_ajouter->setGeometry(QRect(320, 70, 113, 20));
        label_13 = new QLabel(tab_16);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(260, 110, 61, 21));
        label_31 = new QLabel(tab_16);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(130, 170, 181, 21));
        region_mat_maint_a_ajouter = new QLineEdit(tab_16);
        region_mat_maint_a_ajouter->setObjectName(QString::fromUtf8("region_mat_maint_a_ajouter"));
        region_mat_maint_a_ajouter->setGeometry(QRect(320, 110, 113, 20));
        dateTimeEdit = new QDateTimeEdit(tab_16);
        dateTimeEdit->setObjectName(QString::fromUtf8("dateTimeEdit"));
        dateTimeEdit->setGeometry(QRect(320, 170, 194, 22));
        label_78 = new QLabel(tab_16);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(0, 0, 681, 281));
        label_78->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        ajouter_mat_maintenace = new QPushButton(tab_16);
        ajouter_mat_maintenace->setObjectName(QString::fromUtf8("ajouter_mat_maintenace"));
        ajouter_mat_maintenace->setGeometry(QRect(580, 240, 75, 23));
        frame = new QFrame(tab_16);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(510, 70, 120, 80));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        tabWidget_5->addTab(tab_16, QString());
        label_78->raise();
        label_11->raise();
        label_12->raise();
        ref_mat_maint_a_ajouter->raise();
        nom_mat_maint_a_ajouter->raise();
        label_13->raise();
        label_31->raise();
        region_mat_maint_a_ajouter->raise();
        dateTimeEdit->raise();
        ajouter_mat_maintenace->raise();
        frame->raise();
        tab_17 = new QWidget();
        tab_17->setObjectName(QString::fromUtf8("tab_17"));
        label_15 = new QLabel(tab_17);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(230, 30, 101, 21));
        label_16 = new QLabel(tab_17);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(160, 70, 131, 21));
        lineEdit_18 = new QLineEdit(tab_17);
        lineEdit_18->setObjectName(QString::fromUtf8("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(300, 30, 113, 20));
        lineEdit_19 = new QLineEdit(tab_17);
        lineEdit_19->setObjectName(QString::fromUtf8("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(300, 70, 113, 20));
        label_17 = new QLabel(tab_17);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(200, 120, 91, 21));
        lineEdit_21 = new QLineEdit(tab_17);
        lineEdit_21->setObjectName(QString::fromUtf8("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(300, 120, 113, 20));
        label_34 = new QLabel(tab_17);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(60, 190, 51, 21));
        label_35 = new QLabel(tab_17);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(120, 190, 51, 21));
        dateTimeEdit_3 = new QDateTimeEdit(tab_17);
        dateTimeEdit_3->setObjectName(QString::fromUtf8("dateTimeEdit_3"));
        dateTimeEdit_3->setGeometry(QRect(140, 190, 194, 22));
        label_38 = new QLabel(tab_17);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(360, 190, 31, 21));
        dateTimeEdit_4 = new QDateTimeEdit(tab_17);
        dateTimeEdit_4->setObjectName(QString::fromUtf8("dateTimeEdit_4"));
        dateTimeEdit_4->setGeometry(QRect(380, 190, 194, 22));
        label_77 = new QLabel(tab_17);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(0, 0, 681, 281));
        label_77->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        pushButton_6 = new QPushButton(tab_17);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(580, 240, 75, 23));
        tabWidget_5->addTab(tab_17, QString());
        label_77->raise();
        label_15->raise();
        label_16->raise();
        lineEdit_18->raise();
        lineEdit_19->raise();
        label_17->raise();
        lineEdit_21->raise();
        label_34->raise();
        label_35->raise();
        dateTimeEdit_3->raise();
        label_38->raise();
        dateTimeEdit_4->raise();
        pushButton_6->raise();
        tab_18 = new QWidget();
        tab_18->setObjectName(QString::fromUtf8("tab_18"));
        label_18 = new QLabel(tab_18);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 130, 211, 21));
        ref_mat_maint_a_supp1 = new QLineEdit(tab_18);
        ref_mat_maint_a_supp1->setObjectName(QString::fromUtf8("ref_mat_maint_a_supp1"));
        ref_mat_maint_a_supp1->setGeometry(QRect(230, 130, 113, 20));
        label_79 = new QLabel(tab_18);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(0, 0, 681, 291));
        label_79->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        supprimer_mat_maintenace1 = new QPushButton(tab_18);
        supprimer_mat_maintenace1->setObjectName(QString::fromUtf8("supprimer_mat_maintenace1"));
        supprimer_mat_maintenace1->setGeometry(QRect(570, 240, 75, 23));
        tabWidget_5->addTab(tab_18, QString());
        label_79->raise();
        label_18->raise();
        ref_mat_maint_a_supp1->raise();
        supprimer_mat_maintenace1->raise();
        tab_19 = new QWidget();
        tab_19->setObjectName(QString::fromUtf8("tab_19"));
        tableView_2 = new QTableView(tab_19);
        tableView_2->setObjectName(QString::fromUtf8("tableView_2"));
        tableView_2->setGeometry(QRect(10, 10, 271, 251));
        label_19 = new QLabel(tab_19);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(390, 20, 51, 21));
        label_20 = new QLabel(tab_19);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(380, 100, 71, 21));
        lineEdit_8 = new QLineEdit(tab_19);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(450, 100, 113, 20));
        label_80 = new QLabel(tab_19);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(0, 0, 681, 281));
        label_80->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/dddddddddd.jpg")));
        pushButton_12 = new QPushButton(tab_19);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(580, 100, 75, 23));
        comboBox_3 = new QComboBox(tab_19);
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->setObjectName(QString::fromUtf8("comboBox_3"));
        comboBox_3->setGeometry(QRect(450, 20, 69, 22));
        label_51 = new QLabel(tab_19);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(400, 190, 251, 21));
        pushButton_20 = new QPushButton(tab_19);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(480, 230, 75, 23));
        tabWidget_5->addTab(tab_19, QString());
        label_80->raise();
        tableView_2->raise();
        label_19->raise();
        label_20->raise();
        lineEdit_8->raise();
        pushButton_12->raise();
        comboBox_3->raise();
        label_51->raise();
        pushButton_20->raise();
        label_14 = new QLabel(tab_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(-10, -10, 741, 391));
        label_14->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/design Qt/back.jpg")));
        ges->addTab(tab_3, QString());
        label_14->raise();
        tabWidget_5->raise();

        retranslateUi(Dialog);

        ges->setCurrentIndex(2);
        tabWidget_2->setCurrentIndex(3);
        tabWidget_6->setCurrentIndex(3);
        tabWidget_5->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QCoreApplication::translate("Dialog", "Dialog", nullptr));
#if QT_CONFIG(tooltip)
        tabWidget_2->setToolTip(QCoreApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Afficher </span></p></body></html>", nullptr));
#endif // QT_CONFIG(tooltip)
        label->setText(QCoreApplication::translate("Dialog", "Referance:", nullptr));
        label_2->setText(QCoreApplication::translate("Dialog", "Nom du materiel :", nullptr));
        label_3->setText(QCoreApplication::translate("Dialog", "Etat :", nullptr));
        ajouterEtatMateriauxPoss1->setText(QCoreApplication::translate("Dialog", "bonne etat", nullptr));
        ajouteretatMateriauxposs0->setText(QCoreApplication::translate("Dialog", "mauvaise etat ", nullptr));
        label_84->setText(QString());
        ajouterposs->setText(QCoreApplication::translate("Dialog", "Ajouter", nullptr));
        comboetatajouter->setItemText(0, QCoreApplication::translate("Dialog", "Bonne", nullptr));
        comboetatajouter->setItemText(1, QCoreApplication::translate("Dialog", "Mauvaise", nullptr));

        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QCoreApplication::translate("Dialog", "ajouter", nullptr));
        label_83->setText(QString());
        pushButton_4->setText(QCoreApplication::translate("Dialog", "Modifier", nullptr));
        label_4->setText(QCoreApplication::translate("Dialog", "Referance:", nullptr));
        label_5->setText(QCoreApplication::translate("Dialog", "Etat :", nullptr));
        label_6->setText(QCoreApplication::translate("Dialog", "Nom du materiel:", nullptr));
        mat_poss_etat_b_mod->setText(QCoreApplication::translate("Dialog", "bonne ", nullptr));
        mat_poss_m__mod->setText(QCoreApplication::translate("Dialog", "mauvaise", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QCoreApplication::translate("Dialog", "modifier", nullptr));
        label_8->setText(QCoreApplication::translate("Dialog", "Entrer la referance du materiel \303\240 supprimer :", nullptr));
        label_82->setText(QString());
        supp_mat_poss1->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_7), QCoreApplication::translate("Dialog", "supprimer", nullptr));
        label_9->setText(QCoreApplication::translate("Dialog", "Trier par :", nullptr));
        label_10->setText(QCoreApplication::translate("Dialog", "Rechercher :", nullptr));
        label_81->setText(QString());
        pushButton_10->setText(QCoreApplication::translate("Dialog", "Afficher", nullptr));
        comboBox_5->setItemText(0, QCoreApplication::translate("Dialog", "Nom", nullptr));
        comboBox_5->setItemText(1, QCoreApplication::translate("Dialog", "Matricule", nullptr));

        pushButton_13->setText(QCoreApplication::translate("Dialog", "Afficher", nullptr));
        label_37->setText(QCoreApplication::translate("Dialog", "selectionner la referance du materiel \303\240 supprimer :", nullptr));
        pushButton_14->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QCoreApplication::translate("Dialog", "afficher", nullptr));
        ges->setTabText(ges->indexOf(tab), QCoreApplication::translate("Dialog", "materiaux en possessions", nullptr));
        label_21->setText(QCoreApplication::translate("Dialog", "Referance :", nullptr));
        label_22->setText(QCoreApplication::translate("Dialog", "nom du mateiel manquant:", nullptr));
        label_23->setText(QCoreApplication::translate("Dialog", "Prix :", nullptr));
        label_88->setText(QString());
        ajoutermateriauxmanq->setText(QCoreApplication::translate("Dialog", "Ajouter", nullptr));
        label_7->setText(QCoreApplication::translate("Dialog", "Disponibilit\303\251:", nullptr));
        dispo_oui->setText(QCoreApplication::translate("Dialog", "Oui", nullptr));
        dispo_non->setText(QCoreApplication::translate("Dialog", "Non", nullptr));
        tabWidget_6->setTabText(tabWidget_6->indexOf(tab_20), QCoreApplication::translate("Dialog", "ajouter", nullptr));
        label_25->setText(QCoreApplication::translate("Dialog", " referance :", nullptr));
        label_26->setText(QCoreApplication::translate("Dialog", " nom du mateiel :", nullptr));
        label_27->setText(QCoreApplication::translate("Dialog", " prix :", nullptr));
        label_85->setText(QString());
        pushButton_5->setText(QCoreApplication::translate("Dialog", "Modifier", nullptr));
        label_24->setText(QCoreApplication::translate("Dialog", "Disponibilit\303\251:", nullptr));
        radioButton_9->setText(QCoreApplication::translate("Dialog", "Oui", nullptr));
        radioButton_10->setText(QCoreApplication::translate("Dialog", "Non", nullptr));
        tabWidget_6->setTabText(tabWidget_6->indexOf(tab_21), QCoreApplication::translate("Dialog", "modifier", nullptr));
        label_28->setText(QCoreApplication::translate("Dialog", "Entrer la referance du materiel \303\240 supprimer :", nullptr));
        label_86->setText(QString());
        supprimermatmanq1->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget_6->setTabText(tabWidget_6->indexOf(tab_22), QCoreApplication::translate("Dialog", "supprimer", nullptr));
        label_29->setText(QCoreApplication::translate("Dialog", "Trier par :", nullptr));
        label_30->setText(QCoreApplication::translate("Dialog", "Rechercher :", nullptr));
        label_87->setText(QString());
        pushButton_11->setText(QCoreApplication::translate("Dialog", "Afficher", nullptr));
        comboBox_4->setItemText(0, QCoreApplication::translate("Dialog", "Nom", nullptr));
        comboBox_4->setItemText(1, QCoreApplication::translate("Dialog", "Matricule", nullptr));

        label_50->setText(QCoreApplication::translate("Dialog", "selectionner la referance du materiel \303\240 supprimer :", nullptr));
        pushButton_19->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget_6->setTabText(tabWidget_6->indexOf(tab_23), QCoreApplication::translate("Dialog", "afficher", nullptr));
        ges->setTabText(ges->indexOf(tab_2), QCoreApplication::translate("Dialog", "materiaux manquants", nullptr));
        label_11->setText(QCoreApplication::translate("Dialog", "referance :", nullptr));
        label_12->setText(QCoreApplication::translate("Dialog", "nom du mateiel :", nullptr));
        label_13->setText(QCoreApplication::translate("Dialog", "region :", nullptr));
        label_31->setText(QCoreApplication::translate("Dialog", "le materiel en maintenace jusqu'a :", nullptr));
        label_78->setText(QString());
        ajouter_mat_maintenace->setText(QCoreApplication::translate("Dialog", "Ajouter", nullptr));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_16), QCoreApplication::translate("Dialog", "ajouter", nullptr));
        label_15->setText(QCoreApplication::translate("Dialog", " referance :", nullptr));
        label_16->setText(QCoreApplication::translate("Dialog", "nouveau nom du mateiel :", nullptr));
        label_17->setText(QCoreApplication::translate("Dialog", "nouvelle region :", nullptr));
        label_34->setText(QCoreApplication::translate("Dialog", "dur\303\251e :", nullptr));
        label_35->setText(QCoreApplication::translate("Dialog", "du ", nullptr));
        label_38->setText(QCoreApplication::translate("Dialog", "\303\240", nullptr));
        label_77->setText(QString());
        pushButton_6->setText(QCoreApplication::translate("Dialog", "Modifier", nullptr));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_17), QCoreApplication::translate("Dialog", "modifier", nullptr));
        label_18->setText(QCoreApplication::translate("Dialog", "Entrer la referance du materiel \303\240 supprimer :", nullptr));
        label_79->setText(QString());
        supprimer_mat_maintenace1->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_18), QCoreApplication::translate("Dialog", "supprimer", nullptr));
        label_19->setText(QCoreApplication::translate("Dialog", "Trier par :", nullptr));
        label_20->setText(QCoreApplication::translate("Dialog", "Rechercher :", nullptr));
        label_80->setText(QString());
        pushButton_12->setText(QCoreApplication::translate("Dialog", "Afficher", nullptr));
        comboBox_3->setItemText(0, QCoreApplication::translate("Dialog", "Nom", nullptr));
        comboBox_3->setItemText(1, QCoreApplication::translate("Dialog", "Matricule", nullptr));

        label_51->setText(QCoreApplication::translate("Dialog", "selectionner la referance du materiel \303\240 supprimer :", nullptr));
        pushButton_20->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_19), QCoreApplication::translate("Dialog", "afficher", nullptr));
        ges->setTabText(ges->indexOf(tab_3), QCoreApplication::translate("Dialog", "materiaux en maintenace ", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NIZAR_H
