--------------------------------------------------------
--  Fichier créé - jeudi-avril-29-2021   
--------------------------------------------------------
DROP TABLE "YASSINE"."CARTE_FID";
DROP TABLE "YASSINE"."CLIENT";
DROP TABLE "YASSINE"."COMANDE";
DROP TABLE "YASSINE"."COMMANDEV";
DROP TABLE "YASSINE"."DEPARTEMENT";
DROP TABLE "YASSINE"."EMPLOYER";
DROP TABLE "YASSINE"."EQUIPEMENT";
DROP TABLE "YASSINE"."FOURNISSEUR";
DROP TABLE "YASSINE"."MAINTENANCE";
DROP TABLE "YASSINE"."PRODUIT";
--------------------------------------------------------
--  DDL for Table CARTE_FID
--------------------------------------------------------

  CREATE TABLE "YASSINE"."CARTE_FID" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"PT" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "YASSINE"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(50 BYTE), 
	"TEL" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMANDE
--------------------------------------------------------

  CREATE TABLE "YASSINE"."COMANDE" 
   (	"ID" NUMBER(4,0), 
	"QUANTITE" VARCHAR2(30 BYTE), 
	"FOURNISSEUR" VARCHAR2(30 BYTE), 
	"CLIENT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDEV
--------------------------------------------------------

  CREATE TABLE "YASSINE"."COMMANDEV" 
   (	"ID" NUMBER, 
	"PRODUIT" VARCHAR2(20 BYTE), 
	"DATEP" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTEMENT
--------------------------------------------------------

  CREATE TABLE "YASSINE"."DEPARTEMENT" 
   (	"ID_DEPP" NUMBER, 
	"SPECIALITE" VARCHAR2(50 BYTE), 
	"GERANT" VARCHAR2(50 BYTE), 
	"LOCALISATION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYER
--------------------------------------------------------

  CREATE TABLE "YASSINE"."EMPLOYER" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"SALAIRE" NUMBER, 
	"NUMERO" NUMBER, 
	"ID_DEPP" NUMBER, 
	"SERVICE" VARCHAR2(50 BYTE), 
	"MDP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "YASSINE"."EQUIPEMENT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"ETAT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "YASSINE"."FOURNISSEUR" 
   (	"ID" NUMBER, 
	"PRENOM" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"NUMERO" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "YASSINE"."MAINTENANCE" 
   (	"ID" NUMBER, 
	"DATE_M" VARCHAR2(100 BYTE), 
	"PRIX" NUMBER, 
	"ID_EQP" NUMBER, 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "YASSINE"."PRODUIT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YASSINE.CARTE_FID
SET DEFINE OFF;
Insert into YASSINE.CARTE_FID (ID,TYPE,PT,ID_CLIENT) values ('1','premium','7895','26');
Insert into YASSINE.CARTE_FID (ID,TYPE,PT,ID_CLIENT) values ('454','ggggggg','0','1');
Insert into YASSINE.CARTE_FID (ID,TYPE,PT,ID_CLIENT) values ('7','gold edition','5000','1');
REM INSERTING into YASSINE.CLIENT
SET DEFINE OFF;
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('1','gharbi','yassine','atou26.ag@gmail.com','90128026');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('74','fdf','vdv','vdv','27303703');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('48','gretge','erger','rgeerg','8455454');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('485','vdvd','dvvd','dvvd','5544554');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('454','ugutg','rgg','fkhre','0');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('78','moussa','amine','amine.moussa@gmail.com','90128026');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('26','pppp','pppp','pppp@gmail.com','77777777');
Insert into YASSINE.CLIENT (CIN,NOM,PRENOM,MAIL,TEL) values ('928','ggggg','jbfkjsfiujbgf','gdyfusfigizfugzof','78945687');
REM INSERTING into YASSINE.COMANDE
SET DEFINE OFF;
Insert into YASSINE.COMANDE (ID,QUANTITE,FOURNISSEUR,CLIENT) values ('1','2','houssem','yassine');
Insert into YASSINE.COMANDE (ID,QUANTITE,FOURNISSEUR,CLIENT) values ('2','13','yassine','houssem');
Insert into YASSINE.COMANDE (ID,QUANTITE,FOURNISSEUR,CLIENT) values ('5','5','gyh','ughj');
REM INSERTING into YASSINE.COMMANDEV
SET DEFINE OFF;
Insert into YASSINE.COMMANDEV (ID,PRODUIT,DATEP,PRIX,QUANTITE) values ('1','nestle','01/01/2021','13','14');
REM INSERTING into YASSINE.DEPARTEMENT
SET DEFINE OFF;
Insert into YASSINE.DEPARTEMENT (ID_DEPP,SPECIALITE,GERANT,LOCALISATION) values ('1','gjk','kk','yfyfg');
Insert into YASSINE.DEPARTEMENT (ID_DEPP,SPECIALITE,GERANT,LOCALISATION) values ('3','jjj','jjj','jjj');
Insert into YASSINE.DEPARTEMENT (ID_DEPP,SPECIALITE,GERANT,LOCALISATION) values ('2',null,'oplm','oplm');
REM INSERTING into YASSINE.EMPLOYER
SET DEFINE OFF;
Insert into YASSINE.EMPLOYER (ID,NOM,PRENOM,SALAIRE,NUMERO,ID_DEPP,SERVICE,MDP) values ('1','mmmmm','tfyghj','444','444','1',null,null);
Insert into YASSINE.EMPLOYER (ID,NOM,PRENOM,SALAIRE,NUMERO,ID_DEPP,SERVICE,MDP) values ('5','kk','ll','124','147','3','User','kkk');
Insert into YASSINE.EMPLOYER (ID,NOM,PRENOM,SALAIRE,NUMERO,ID_DEPP,SERVICE,MDP) values ('10','kakak','kakaka','144','123','1','Administrateur','alc');
REM INSERTING into YASSINE.EQUIPEMENT
SET DEFINE OFF;
REM INSERTING into YASSINE.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into YASSINE.MAINTENANCE
SET DEFINE OFF;
REM INSERTING into YASSINE.PRODUIT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."CLIENT_PK" ON "YASSINE"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CARTE_FID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."CARTE_FID_PK" ON "YASSINE"."CARTE_FID" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAINTENANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."MAINTENANCE_PK" ON "YASSINE"."MAINTENANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."PRODUIT_PK" ON "YASSINE"."PRODUIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."DEPARTEMENT_PK" ON "YASSINE"."DEPARTEMENT" ("ID_DEPP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."EMPLOYER_PK" ON "YASSINE"."EMPLOYER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."EQUIPEMENT_PK" ON "YASSINE"."EQUIPEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."FOURNISSEUR_PK" ON "YASSINE"."FOURNISSEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDEV
--------------------------------------------------------

  ALTER TABLE "YASSINE"."COMMANDEV" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMMANDEV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMMANDEV" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMMANDEV" MODIFY ("DATEP" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMMANDEV" MODIFY ("PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARTE_FID
--------------------------------------------------------

  ALTER TABLE "YASSINE"."CARTE_FID" ADD CONSTRAINT "CARTE_FID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."CARTE_FID" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CARTE_FID" MODIFY ("PT" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CARTE_FID" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CARTE_FID" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "YASSINE"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."EQUIPEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "YASSINE"."MAINTENANCE" ADD CONSTRAINT "MAINTENANCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."MAINTENANCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."FOURNISSEUR" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."FOURNISSEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."FOURNISSEUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTEMENT
--------------------------------------------------------

  ALTER TABLE "YASSINE"."DEPARTEMENT" ADD CONSTRAINT "DEPARTEMENT_PK" PRIMARY KEY ("ID_DEPP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."DEPARTEMENT" MODIFY ("ID_DEPP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMANDE
--------------------------------------------------------

  ALTER TABLE "YASSINE"."COMANDE" MODIFY ("CLIENT" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMANDE" MODIFY ("FOURNISSEUR" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMANDE" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."COMANDE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "YASSINE"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYER
--------------------------------------------------------

  ALTER TABLE "YASSINE"."EMPLOYER" ADD CONSTRAINT "EMPLOYER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."EMPLOYER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "YASSINE"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."PRODUIT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."PRODUIT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARTE_FID
--------------------------------------------------------

  ALTER TABLE "YASSINE"."CARTE_FID" ADD CONSTRAINT "CARTE_FID_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "YASSINE"."CLIENT" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYER
--------------------------------------------------------

  ALTER TABLE "YASSINE"."EMPLOYER" ADD CONSTRAINT "EMPLOYER_FK1" FOREIGN KEY ("ID_DEPP")
	  REFERENCES "YASSINE"."DEPARTEMENT" ("ID_DEPP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "YASSINE"."MAINTENANCE" ADD CONSTRAINT "MAINTENANCE_FK1" FOREIGN KEY ("ID_EQP")
	  REFERENCES "YASSINE"."EQUIPEMENT" ("ID") ENABLE;
